# Generated by Django 5.2.4 on 2025-09-13 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='broker_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trackers.brokeraccount'),
            preserve_default=False,
        ),
    ]
