# Generated by Django 5.2.4 on 2025-09-13 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_holding_broker_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_holdings', to='trackers.underlyingasset'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_holdings', to='trackers.fund'),
        ),
    ]
