# Generated by Django 5.2.4 on 2025-09-13 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_alter_holding_asset_alter_holding_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_holdings', to='trackers.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='trackers.fund'),
        ),
    ]
